# Generated by Django 5.0.2 on 2024-02-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rider", "0002_rider__display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="_display_name",
            field=models.CharField(
                blank=True,
                db_column="display_name",
                default="",
                max_length=100,
                verbose_name="Display Name",
            ),
        ),
    ]
