# Generated by Django 4.0.5 on 2022-06-30 07:42

from django.db import migrations, models


def forward(apps, schema_editor):
    Time = apps.get_model("leaderboard", "Time")
    db_alias = schema_editor.connection.alias

    Time.objects.using(db_alias).update(total_ms=models.F("time_ms"))


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0002_time_create_date_time_timer"),
    ]

    operations = [
        migrations.AddField(
            model_name="time",
            name="penalty_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="time",
            name="total_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(forward, lambda _, __: None),
    ]
