# Generated by Django 5.0.3 on 2024-03-31 21:05

import gk.leaderboard.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0004_series_course_create_date_course_modify_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": [
                    models.OrderBy(models.F("series__order")),
                    models.OrderBy(models.F("series__create_date"), descending=True),
                    models.OrderBy(models.F("create_date"), descending=True),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ["-order"]},
        ),
        migrations.AddField(
            model_name="course",
            name="layout_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=gk.leaderboard.models._layout_path
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="route_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=gk.leaderboard.models._route_path
            ),
        ),
    ]
