---

- name: Install networking packages
  ansible.builtin.apt:
    state: present
    pkg: 
     - ufw
     - udhcpd

- name: uDHCPd configuration
  ansible.builtin.template:
    src: dhcpd/udhcpd.conf.j2
    dest: /etc/udhcpd.conf

- name: Start uDHCPd
  ansible.builtin.systemd_service:
    name: udhcpd
    state: started
    enabled: true

- name: Enable Wifi Hotspot
  community.general.nmcli:
    type: wifi
    conn_name: "{{ hotspot_ssid }}_ap"
    ifname: "{{ hotspot_interface }}"
    ssid: "{{ hotspot_ssid }}"
    ip4: "{{ hotspot_net | ansible.utils.ipaddr('net') | ansible.utils.ipaddr('1') }}"
    wifi:
      mode: ap
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ hotspot_password }}"
    autoconnect: true
    state: present

- name: Firewall allow out
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Firewall deny in
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Firewall allow services
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - ssh
    - bootps
    - bootpc

- name: Firewall enable
  community.general.ufw:
    state: enabled
