python_sources(
    dependencies=[
        "src/python/gk/leaderboard/migrations",
        "src/python/gk/leaderboard/templates",
        "3rdparty:requirements.txt#Pillow",
    ]
)

python_tests(
    name="tests",
)
