---
- name: Docker
  hosts: 
   - webservers
   - mosquitto
  roles: 
   # - geerlingguy.docker

- name: Webserver-Setup
  hosts:
    - webservers
  tasks:
    - name: Caddy Dir
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0700
      with_items: 
        - /etc/caddy
        - /etc/gk
        - /var/gk/web
        - /var/gk/web/media
        - /var/gk/web/static

    - name: Secrets
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        mode: 0600
        decrypt: true
      with_items:
        - {src: web.SECRET_KEY, dst: /etc/gk/web.SECRET_KEY}

    - name: Caddyfile
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: /etc/caddy/Caddyfile

    - name: Network
      community.docker.docker_network:
        name: web
        
    - name: Run Caddy
      community.docker.docker_container:
        name: caddy
        image: caddy:latest
        state: started
        restart: true
        restart_policy: always
        pull: always
        networks: 
          - name: web
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"
        volumes:
          - "/etc/caddy:/etc/caddy"
          - "/var/gk/web/media:/var/gk/web/media"
          - "/var/gk/web/static:/var/gk/web/static"

    - name: Run App
      community.docker.docker_container:
        name: web
        image: ghcr.io/xlevus/gymkhana/web:latest
        state: started
        pull: always
        restart: true
        volumes:
          - "/etc/gk/web.SECRET_KEY:/etc/SECRET_KEY"
          - "/var/gk/web:/data"
        networks: 
          - name: web
        env:
          DEBUG: "False"
          ALLOWED_HOSTS: "srv501663.hstgr.cloud,leaderboard.coneheads.org"
          CSRF_TRUSTED_ORIGINS: "https://srv501663.hstgr.cloud,https://leaderboard.coneheads.org"
          DATABASE_URL: "sqlite:///data/db.sqlite"
          SECRET_KEY_FILE: "/etc/SECRET_KEY"
          STATIC_ROOT: "/data/static"
          MEDIA_ROOT: "/data/media"
          MEDIA_URL: "/media/"

- name: Mosquitto
  hosts:
  - mosquitto
  tasks:
    - name: Mosquitto Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0700
      with_items: 
        - /etc/mosquitto

    - name: Mosquitto Config
      ansible.builtin.copy: 
        src: mosquitto/mosquitto.conf
        dest: /etc/mosquitto/mosquitto.conf

    - name: Mosquitto Passwords
      community.docker.docker_container:
        name: mqtt-passwd
        image: eclipse-mosquitto:latest
        detach: false
        command: "mosquitto_passwd -b /mosquitto/config/passwd {{ item.key }} {{ item.value }}"
        volumes:
          - "/etc/mosquitto/passwd:/mosquitto/config/passwd"
      no_log: true
      loop: "{{ mosquitto_users|dict2items }}"
      vars:
        mosquitto_users:
          gymkhana: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            64343437653430373430303264633266303333656437636330346538333039363332313639356266
            6165393664646332303062343464653238616634353733340a363832633936383639396234303366
            63636362393437653834383564396136386337366362383066633864396131323564346436346365
            3130313466383865390a656231626331633835616530663234353739613731343935363062393164
            37623366643835333531393434666432623365666536393164363363646533386666

    - name: Run Mosquitto
      community.docker.docker_container:
        name: mqtt
        image: eclipse-mosquitto:latest
        volumes:
          - "/etc/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.config"
          - "/etc/mosquitto/passwd:/mosquitto/config/passwd"

