name: Test
on: [push]
env:
  PANTS_CONFIG_FILES: +['pants.ci.toml']
jobs:
  test:
    steps:
      - name: Init Pyenv
        uses: pantsbuild/actions/pyenv@main

      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          # cache0 makes it easy to bust the cache if needed
          gha-cache-key: cache0-py${{ matrix.python_version }}
          named-caches-hash: ${{ hashFiles('lockfiles/*.json', '**/something-else.lock') }}